name: Deploy to Firebase Web Hosting
on:
  push:
    branches: 
      - server

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: npm i -g heroku
    - run: git checkout -b server
    - run: git remote add heroku git@heroku.com:omg-api.git
    - run: [ -e ~/.ssh ] || mkdir .ssh
    - run: echo ${{secrets.HEROKU_SSH_KEY}}>~/.ssh/id_rsa
    - run: eval `ssh-agent`
    - run: ssh-add ~/.ssh/id_rsa
    - run: git push heroku master --signed=true --force

