name: Vue

on:
  push:
    branch: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: rm -rf ./docs >/dev/null 2>&1
      - run: npm install
      - run: ls -lA
      - run: node bin/deploy.js
